logging:
  level:
    root: warn
    sql: warn
    org.springframework.web: warn
    org.springframework.jdbc: warn
    org.flywaydb: warn

server:
  port: 8080



spring:
  flyway:
    baseline:
      on:
        migrate: true

  main:
    banner-mode: off

  application:
    name: ExambyteProjekt

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

#
  datasource:
    # Use DB_PASSWORD if available, otherwise ‘iamgroot’ as local fallback
    password: ${DB_PASSWORD:iamgroot}
    username: ${DB_USER:user}
    url: jdbc:postgresql://localhost:5435/exambyte

exambyte:
  rollen:
    # ----------------- Enter your GitHub name here -----------------
    studenten: Kxrstin
    korrektoren: Kxrstin
    organisatoren: Kxrstin