logging:
  level:
    root: error

server:
  port: 8080

spring:
  main:
    banner:
      mode: off

  application:
    name: ExambyteProjekt

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

exambyte:
  rollen:
    studenten: Kxrstin, Narr1M
    korrektoren: Kxrstin, Narr1M
    organisatoren: Kxrstin, Narr1M