logging:
  level:
    root: error
    sql: error
    org.springframework.web: error
    org.springframework.jdbc: error
    org.flywaydb: error

server:
  port: 8080



spring:
  flyway:
    baseline:
      on:
        migrate: true

  main:
    banner-mode: off

  application:
    name: ExambyteProjekt

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

  datasource:
    password: iamgroot
    username: user
    url: jdbc:postgresql://localhost:5435/exambyte

exambyte:
  rollen:
    studenten: Kxrstin, Narr1M
    korrektoren: Kxrstin, Narr1M
    organisatoren: Kxrstin, Narr1M